name: IronNetwork
version: '${project.version}'
main: com.envyus.ironnetwork.IronNetwork
api-version: '1.20'
commands:
  god:
    description: Become a God.
    usage: /<command>
  feed:
    description: Feed your hungry.
    usage: /<command>
  fly:
    description: aaa
    usage: aa